### ISSUE TITLE
Unable to obtain monitoring channel status

### ISSUE THREAD

**Issue by yigiwoliao** [libc0607/rtl88x2cu-20230728#1]
I can switch wlan0 to monitor mode, and set the monitoring channel successful.
But when I want to obtain monitoring channel status, it still shows channel is 1.
I can sure the channel status isn't 1 by using Wireshark captured wireless packets.

```

root@kali:~# airmon-ng start wlan0


PHY     Interface       Driver          Chipset

phy0    wlan0           rtl88x2cu       Realtek Semiconductor Corp. 802.11ac NIC
                (monitor mode enabled)

root@kali:~# 
root@kali:~# iwconfig
lo        no wireless extensions.

eth0      no wireless extensions.

wlan0     unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Monitor  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

root@kali:~# 
root@kali:~# iw dev wlan0 set channel 6
root@kali:~# 
root@kali:~# iw dev wlan0 info
Interface wlan0
        ifindex 3
        wdev 0x1
        addr 90:de:80:68:b1:5b
        type monitor
        wiphy 0
        channel 1 (2412 MHz), width: 20 MHz, center1: 2412 MHz
        txpower -100.00 dBm
root@kali:~# 
root@kali:~# 
Linux kali 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64 GNU/Linux
root@kali:~# 

```

**Comment by libc0607** [comment]
Yes, that's a bug proudly written by Realtek, and it affects almost all drivers (8812eu also). 
Set channel by ```iw```(cfg80211) will not correctly update some internal status, both cfg80211 and WEXT APIs will return a wrong result. 

I didn't dig into that, because setting any channel using ```iwconfig``` (WEXT) seems all right so it was not sth at a high priority. You can set channel by ```iwconfig wlan0 channel 6```, then ```iw wlan0 info``` and ```iwconfig wlan0``` will both return good results. 

But it should be fixed -- I will check that.

**Comment by libc0607** [comment]
Please checkout [commit 5682f5ec](https://github.com/libc0607/rtl88x2cu-20230728/commit/5682f5ec71d666744cdd0cac76df44559f977c7e), I've tried to fix that

**Comment by libc0607** [comment]
I've just tested that and it seems OK. 

Feel free to re-open it if it's not working for your board.
